name: Debian (experimental)

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  build_kwin:
    name: Build (KWin)
    runs-on: ubuntu-latest
    container:
      image: debian:experimental # zizmor: ignore[unpinned-images]
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Refresh Packages
        run: apt-get update

      - name: Upgrade Packages
        run: apt-get upgrade -y

      - name: Install Dependencies
        run: apt-get install -y -f cmake g++ extra-cmake-modules qt6-tools-dev kwin-wayland kwin-dev libkf6configwidgets-dev gettext libkf6kcmutils-dev libyaml-cpp-dev libxkbcommon-dev pkg-config libevdev-dev libdrm-dev

      - name: Configure CMake
        run: cmake -B "${GITHUB_WORKSPACE}/build" -DINPUTACTIONS_BUILD_KWIN=ON

      - name: Build
        run: cmake --build "${GITHUB_WORKSPACE}/build" -j

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true