name: NixOS (Plasma 6.4)

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  build_kwin:
    name: Build (KWin)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31.8.1
        with:
          nix_path: nixpkgs=channel:904c5e4792fd0f82a3bd083366f4942c1570738f # Plasma 6.4.5

      - name: Patch flake.nix
        run: sed -i -e 's/nixos-unstable/904c5e4792fd0f82a3bd083366f4942c1570738f/g' flake.nix

      - name: Update flake.lock
        run: nix flake update

      - name: Build
        run: nix build -L .#inputactions-kwin

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true